name: Build, Test, Analyze and Publish Packages

on:
  push:
    branches:
      - main

jobs:
  build-test-analyze-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com/'

    # ATM
    - name: Install ATM dependencies
      run: |
        cd atm
        npm install

    - name: Run ATM tests
      run: |
        cd atm
        npm run test:cov

    - name: Analyze ATM with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        projectBaseDir: atm
        args: >
          -Dsonar.projectKey=upt-faing-epis_atm_lupaca
          -Dsonar.organization=upt-faing-epis
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

    - name: Publish ATM package
      run: |
        cd atm
        npm version patch
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # PAYMENT
    - name: Install Payment dependencies
      run: |
        cd payment
        npm install

    - name: Run Payment tests
      run: |
        cd payment
        npm run test:cov

    - name: Analyze Payment with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        projectBaseDir: payment
        args: >
          -Dsonar.projectKey=upt-faing-epis_payment_lupaca
          -Dsonar.organization=upt-faing-epis
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

    - name: Publish Payment package
      run: |
        cd payment
        npm version patch
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
