name: Build, Test and Publish Packages

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com/'

    # ATM package
    - name: Install ATM dependencies
      run: |
        cd atm
        npm install

    - name: Run ATM tests
      run: |
        cd atm
        npx jest --coverage

    - name: Publish ATM package
      run: |
        cd atm
        npm version patch
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # PAYMENT package
    - name: Install Payment dependencies
      run: |
        cd payment
        npm install

    - name: Run Payment tests
      run: |
        cd payment
        npx jest --coverage

    - name: Publish Payment package
      run: |
        cd payment
        npm version patch
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
